### ISSUE TITLE
Federated share notifications pop-up is blank

### ISSUE THREAD

**Issue by rev138** [nextcloud/notifications#232]
### Steps to reproduce
1. Get a federated share notification
2. Click on the notifications icon

### Expected behaviour
This should display the notifications in a pop-up dialog

### Actual behaviour
The pop-up is blank if there are notifications. If there are no notifications a message is displayed saying "No notifications"

### Server configuration

**Operating system**: debian 9

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.2

**Nextcloud version:** 15.0.0

**Where did you install Nextcloud from:** tarball

**Signing status:** 

```
No errors have been found.
```

**List of activated apps:**

```

    accessibility: 1.1.0
    calendar: 1.6.4
    circles: 0.15.1
    cloud_federation_api: 0.1.0
    comments: 1.5.0
    contacts: 3.0.0
    data_request: 1.2.0
    dav: 1.8.0
    deck: 0.5.1
    drop_account: 0.0.13
    encryption: 2.3.0
    federatedfilesharing: 1.5.0
    federation: 1.5.0
    files: 1.10.0
    files_antivirus: 2.0.0
    files_automatedtagging: 1.5.0
    files_pdfviewer: 1.4.0
    files_retention: 1.4.0
    files_sharing: 1.7.0
    files_texteditor: 2.7.0
    files_trashbin: 1.5.0
    files_versions: 1.8.0
    files_videoplayer: 1.4.0
    gallery: 18.2.0
    groupfolders: 2.0.2
    logreader: 2.0.0
    lookup_server_connector: 1.3.0
    news: 13.0.3
    nextcloud_announcements: 1.4.0
    notifications: 2.3.0
    oauth2: 1.3.0
    ojsxc: 3.4.3
    password_policy: 1.5.0
    provisioning_api: 1.5.0
    richdocuments: 3.0.6
    serverinfo: 1.5.0
    spreed: 5.0.0
    support: 1.0.0
    systemtags: 1.5.0
    tasks: 0.9.8
    terms_of_service: 1.1.1
    twofactor_backupcodes: 1.4.1
    twofactor_totp: 2.1.0
    workflowengine: 1.5.0
    Disabled:
    activity
    admin_audit
    files_external
    firstrunwizard
    sharebymail
    survey_client
    theming
    updatenotification
    user_external
    user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx",
            "xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": 0,
        "theme": "gibberfish",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/opt\/nextcloud-data\/skeleton_files",
        "enable_previews": true,
        "token_auth_enforced": true,
        "filelocking.enabled": true,
        "updatechecker": false,
        "upgrade.disable-web": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image"
        ],
        "default_language": "en",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "log_rotate_size": 104857600,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": false,
        "maintenance": false,
        "defaultapp": "dashboard,files",
        "knowledgebaseenabled": false,
        "overwriteprotocol": "http",
        "remember_login_cookie_lifetime": 86400
    }
}
```

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox and Vivaldi tested

**Operating system:** Fedora 29

#### Nextcloud log (data/owncloud.log)
```
{"reqId":"K0Ajkhkyuv0FQxjtcgqp","level":3,"time":"2018-12-21T14:59:23+00:00","remoteAddr":"172.18.0.11","user":"xxx","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/opt\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.0.10"}
```

#### Browser log
```
IContent Security Policy: Ignoring duplicate source 'unsafe-inline'
Content Security Policy: Couldn’t parse invalid host 'unsafe-inline'
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
State changed to INITIATING jsxc.min.js:1:2054
Try to relogin jsxc.min.js:1:2054
I am not able to relogin jsxc.min.js:1:2054
State changed to SUSPEND jsxc.min.js:1:2054
TypeError: "this.userRemoteTemplate is not a function"
	parseParameter https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:89179
	parseMessage https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:88921
	forEach https://example.com/core/vendor/core.js?v=71e1b20b:18:2350
	parseMessage https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:88866
	renderedSubject https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:14:23425
	get https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:15827
	evaluate https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:16984
	Re https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:18879
	s https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:14:20633
	_render https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:32580
	r https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:63966
	get https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:15827
	Me https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:15752
	mount https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:63982
	mount https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:63844
	mount https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:86637
	init https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:22357
	f https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:52459
	f https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:52348
	$/< https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:55533
	$ https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:55108
	$/< https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:55258
	$ https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:55108
	$/< https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:55258
	$ https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:55108
	i https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:56860
	_update https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:31552
	r https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:63956
	get https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:15827
	run https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:16718
	Ee https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:14856
	te https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:11328
	Xt https://example.com/apps/notifications/js/notifications.js?v=71e1b20b:7:10834
notifications.js:7:10714
New search handler registered search.js:67:4
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://example.com/apps/ojsxc/js/jsxc/jsxc.min.js?v=71e1b20b
Source Map URL: jsxc.min.js.map[Learn More]
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://example.com/apps/notifications/js/notifications.js?v=71e1b20b
Source Map URL: notifications.js.map[Learn More]
```

**Comment by nickvergessen** [comment]
Seems to be a problem with the JSXC chat app. Can you report your problem there please?

**Comment by victordariovera** [comment]
Same for federated sharing notifications in Chrome v. 71.0.3578.98 and Firefox v.64 (NC v.15, fresh install).

**Comment by violoncelloCH** [comment]
I can reproduce this too as described in https://github.com/nextcloud/server/issues/13228#issuecomment-451315834.
`this.userRemoteTemplate is not a function` -- looks like it's a javascript problem... @nextcloud/javascript could someone take a look at this?

**Comment by skjnldsv** [comment]
@rullzer

**Comment by rakekniven** [comment]
@nickvergessen Should this be working in v15.0.1RC1 ?
Just gave it a try and it still fails.

See https://help.nextcloud.com/t/unable-to-accept-federated-share-invitations-empty-notification-popup/44011 as well

**Comment by nickvergessen** [comment]
No, but in rc2
